// <auto-generated />
namespace OneTouchElectronix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _000333300855 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_000333300855));
        
        string IMigrationMetadata.Id
        {
            get { return "201805130845015_000333300855"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
