// <auto-generated />
namespace OneTouchElectronix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _00111223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_00111223));
        
        string IMigrationMetadata.Id
        {
            get { return "201805131105351_00111223"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
